version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    ignore:
      - dependency-name: 'vue'
        versions: ['4.x']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
