name: CI Pipeline

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']

env:
  NODE_ENV: production
  VITE_BASE_URL: ${{ github.ref == 'refs/heads/main' && '/guess-pokemon/' || '/' }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        run: | 
          npm ci --no-audit --no-fund --include=dev # 完整安装依赖
          npm install npm-run-all --no-audit --no-fund # 安装 npm-run-all
          npm rebuild # 修复可能的二进制文件问题

      - name: Install npm-run-all
        run: npm install npm-run-all --save-dev

      - name: Build Project
        run: npm run build

  deploy-prod:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Notify Slack
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#36a64f'
          SLACK_TITLE: 'Deploy Success'
          SLACK_MESSAGE: 'Production deployment completed'

      - name: Clean Cache
        run: |
          npm cache clean --force
          rm -rf node_modules

      - name: Cache Test Reports
        uses: actions/cache@v3
        with:
          path: |
            coverage
            test-results.xml
          key: ${{ runner.os }}-test-${{ hashFiles('package-lock.json') }}
