name: Sync to Gitee
# 触发规则
on:
  # 推送 main 和 dev 分支时触发
  push:
    branches: ['main', 'dev']
  # 合并请求到 main 分支时触发
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Push to Gitee
        run: |
          git remote add gitee https://Vogadero:${{ secrets.GITEE_TOKEN }}@gitee.com/Vogadero/guess-pokemon.git
          git fetch --unshallow origin # 获取完整提交历史
          git push gitee --all --force # 推送所有分支
          git push gitee --tags --force # 推送所有标签